from datetime import datetime

def generate_creative_brief(platform: str, topic: str, content_output: str) -> str:
    brief = f"""Creative Brief
------------------------
Date: {datetime.now().strftime("%Y-%m-%d")}
Platform: {platform.title()}
Topic: {topic}

Objective:
Create high-performing content optimized for {platform.title()} using brand tone and platform trends.

Summary of Content:
{content_output}

Deliverables:
- Script or caption for {platform}
- Platform-specific CTA
- Hook or visual guidance
- Recommended tags/hashtags (if available)

Notes:
This brief was auto-generated by Project 1 – AI Content Agent v1.
"""
    return brief.strip()